# Generated by Django 4.2.7 on 2023-11-15 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_users_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='users.users')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='users.users')),
            ],
        ),
    ]
